steps:
- name: gcr.io/$PROJECT_ID/remote-builder 
  env: 
    # Use Container Optimized OS 
    # https://cloud.google.com/container-optimized-os/docs/ 
    - INSTANCE_ARGS=--image-project cos-cloud --image-family cos-stable --machine-type=n1-standard-2 
    - ZONE=us-central1-f 
    - USERNAME=cloud-user 
    # Run a script from the local build context in a Docker container 
    - COMMAND=docker run -v /home/cloud-user/workspace:/workspace ubuntu:16.04 bash -xe /workspace/test-scripts/no-op.sh
- name: gcr.io/$PROJECT_ID/remote-builder 
  env: 
    # Use Container Optimized OS 
    # https://cloud.google.com/container-optimized-os/docs/ 
    - INSTANCE_ARGS=--image-project cos-cloud --image-family cos-stable --machine-type=n1-highcpu-32
    - ZONE=europe-west1-b 
    - USERNAME=cloud-user 
    # Run a script from the local build context in a Docker container 
    - COMMAND=docker run -v /home/cloud-user/workspace:/workspace ubuntu:16.04 bash -xe /workspace/test-scripts/no-op.sh
